# Generated by Django 5.0.3 on 2024-04-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='n_cll',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
