# Generated by Django 5.0 on 2024-07-29 18:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telefone', models.IntegerField()),
                ('idade', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='AgendaHairModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabelo', to='core.clientemodel')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaFutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('C1', 'Campo 1'), ('C2', 'Campo 2')], default='C1', max_length=400)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futebol', to='core.clientemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SisoRapidoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('tipo_tratamento', models.CharField(choices=[('LIMPEZA', 'Limpeza'), ('EXTRACAO', 'Extração de Siso'), ('TDC', 'Tratamento de Canal')], default='LIMPEZA', max_length=400)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentista', to='core.clientemodel')),
            ],
        ),
    ]
