# Generated by Django 5.0 on 2024-07-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_agendafutmodel_cliente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClienteModel',
            new_name='Admin',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
    ]
