# Generated by Django 5.0 on 2024-08-02 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_clientemodel_admin_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendafutmodel',
            options={'verbose_name': 'Agenda de Futebol', 'verbose_name_plural': 'Agenda de Futeóis'},
        ),
        migrations.AlterModelOptions(
            name='agendahairmodel',
            options={'verbose_name': 'Agenda de Cabeleireiro'},
        ),
        migrations.AlterModelOptions(
            name='sisorapidomodel',
            options={'verbose_name': 'Agenda de Dentista'},
        ),
        migrations.AlterField(
            model_name='agendafutmodel',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='agendahairmodel',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='sisorapidomodel',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
