# Generated by Django 5.0 on 2024-08-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_agendafutmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendafutmodel',
            name='campo',
            field=models.CharField(choices=[('C1', 'Campo 1'), ('C2', 'Campo 2'), ('C3', 'Campo 3'), ('C4', 'Campo 4')], default='C1', max_length=400),
        ),
    ]
